// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTungpdU5NtDrTFkA3xoPvLmPNUlqZ_c',
    appId: '1:509477884312:web:14a3d4f17e30cee3f1dbed',
    messagingSenderId: '509477884312',
    projectId: 'devlep',
    authDomain: 'devlep.firebaseapp.com',
    storageBucket: 'devlep.appspot.com',
    measurementId: 'G-EQVGWB5MZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjV98l-jixBwXURRKE0lW2FCeoLI2tIwA',
    appId: '1:509477884312:android:d71af5403366b1eef1dbed',
    messagingSenderId: '509477884312',
    projectId: 'devlep',
    storageBucket: 'devlep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD94e8ug4avXn0AwZVSKgHZnBfjIZmPQ0c',
    appId: '1:509477884312:ios:ba9e386cfb268f38f1dbed',
    messagingSenderId: '509477884312',
    projectId: 'devlep',
    storageBucket: 'devlep.appspot.com',
    iosBundleId: 'com.example.develp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD94e8ug4avXn0AwZVSKgHZnBfjIZmPQ0c',
    appId: '1:509477884312:ios:ba9e386cfb268f38f1dbed',
    messagingSenderId: '509477884312',
    projectId: 'devlep',
    storageBucket: 'devlep.appspot.com',
    iosBundleId: 'com.example.develp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuTungpdU5NtDrTFkA3xoPvLmPNUlqZ_c',
    appId: '1:509477884312:web:1bfbf10a26af1399f1dbed',
    messagingSenderId: '509477884312',
    projectId: 'devlep',
    authDomain: 'devlep.firebaseapp.com',
    storageBucket: 'devlep.appspot.com',
    measurementId: 'G-541LMGYCRP',
  );
}
